### ISSUE TITLE
Screen Share button to be added

### ISSUE THREAD

**Issue by akshat0313** [akshat0313/Ak-Meet#2]

**Comment by akr-25** [comment]
Can you assign this issue to me?

**Comment by ArchismanKarmakar** [comment]
> _No description provided._

i want to work, please assign me, i don't know if i can really do this, but i am just giving a try as i just learned webdev

**Comment by ArchismanKarmakar** [comment]
> _No description provided._

i want to work please assign me

**Comment by akshat0313** [comment]
> > _No description provided._
> 
> 
> 
> i want to work please assign me
> 
> 

Yes you can work on this issue.
For this issue you have to add a screen share button in meeting screen just like in Gmeet where a participant can share screen.

**Comment by ArchismanKarmakar** [comment]
> > > _No description provided._
> > 
> > 
> > i want to work please assign me
> 
> Yes you can work on this issue. For this issue you have to add a screen share button in meeting screen just like in Gmeet where a participant can share screen.

yeah i will try but if i fail to do this i will inform you

**Comment by akshat0313** [comment]
> > > > _No description provided._
> 
> > > 
> 
> > > 
> 
> > > i want to work please assign me
> 
> > 
> 
> > Yes you can work on this issue. For this issue you have to add a screen share button in meeting screen just like in Gmeet where a participant can share screen.
> 
> 
> 
> yeah i will try but if i fail to do this i will inform you

Yeah sure.
I will also be helping you for this since this task is hard and also i will add one more tag of bonus in it.
I will give some updates on it in discord.

**Comment by ArchismanKarmakar** [comment]
![scsh-try1](https://user-images.githubusercontent.com/92569441/146648436-fbb72e7d-93ea-43b1-9866-a77cad3b695d.png)




> > > > > _No description provided._
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i want to work please assign me
> > 
> > 
> > > 
> > 
> > 
> > > Yes you can work on this issue. For this issue you have to add a screen share button in meeting screen just like in Gmeet where a participant can share screen.
> > 
> > 
> > yeah i will try but if i fail to do this i will inform you
> 
> Yeah sure. I will also be helping you for this since this task is hard and also i will add one more tag of bonus in it. I will give some updates on it in discord.

here you go. its working. now just i have fix the share position. position i am trying. but sharing is working

**Comment by ArchismanKarmakar** [comment]
> > > > > _No description provided._
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i want to work please assign me
> > 
> > 
> > > 
> > 
> > 
> > > Yes you can work on this issue. For this issue you have to add a screen share button in meeting screen just like in Gmeet where a participant can share screen.
> > 
> > 
> > yeah i will try but if i fail to do this i will inform you
> 
> Yeah sure. I will also be helping you for this since this task is hard and also i will add one more tag of bonus in it. I will give some updates on it in discord.

@akshat0313 #22
