### ISSUE TITLE
Meeting screen design upgradation

### ISSUE THREAD

**Issue by akshat0313** [akshat0313/Ak-Meet#37]
# Description

Design of the meeting screen should be implemented as it is there in the figma link mention below.

# Relevant files

https://www.figma.com/file/F83quCE9FhtMfJMJSa4SaR/Untitled?node-id=0%3A1

**Comment by shmiitg** [comment]
I would like to work on this

**Comment by akshat0313** [comment]
> I would like to work on this

Yes sure
