### ISSUE TITLE
Logout button not working properly

### ISSUE THREAD

**Issue by akshat0313** [akshat0313/Ak-Meet#4]

**Comment by ArchismanKarmakar** [comment]
Sir I have corrected it. Assign me in this I am forking & giving a PR.

**Comment by ArchismanKarmakar** [comment]
> _No description provided._



The disconnect event simply does not work the way you are asking for. That event will fire any time the user navigates to a new page or refreshes the current page. That's how socket.io connections work in the browser. A given connection belongs to a particular page and when a new page is loaded, the prior connection is disconnected and then a new connection is created. There is nothing you can do to change that - that's part of the browser architecture. So, the socket.io disconnect event is simply not the same thing as when your user logs out and can never be the same.

Instead, you need to have your own function that does a logout which the user can trigger by some action in the page. This can be either a socket.io message, an ajax call from your page or by navigating to the logout page. That's how a user can logout and it has nothing to do with the disconnect event.

Similarly, a connect event just means that a user (who may or may not already be logged in) has connected. The login state will be stored in either a cookie or in a server-side session (that is indexed by a cookie).

**Comment by ArchismanKarmakar** [comment]
> _No description provided._

for me I don't no AJAX req so if do this I would rather clear the UID and re-authenticate to /home endpoint, here the /logout endpoint is not working because socket.io is blocking calling of multiple events, so easiest way is to onclick="location.href='/view'"; roomId="";

**Comment by ArchismanKarmakar** [comment]
> _No description provided._
 inside room.ejs
```
<div class="main__controls__block" onclick="location.href=('/view');"">
                <div class="main__controls__button" onclick="location.href=('/view');">
                   <a href="/view"><span class="leave_meeting" onclick="location.href=('/view');">Leave Meeting</span></a>
                </div>
             </div>
```
server.js
`app.get('/view',(req,res) => { res.render('view'); roomId=""; userId="";})`

**Comment by ArchismanKarmakar** [comment]
> _No description provided._

should i create a PR now?

**Comment by akshat0313** [comment]
> > _No description provided._
> 
> 
> 
> should i create a PR now?

Yes you can create a PR now

**Comment by ArchismanKarmakar** [comment]
> > > _No description provided._
> > 
> > 
> > should i create a PR now?
> 
> Yes you can create a PR now

#11 sir please check now.
